-- Entries were AI generated
INSERT INTO INGREDIENTS (INGREDIENT_ID, INGREDIENT_NAME, INGREDIENT_IMAGE_PATH, INGREDIENT_DESCRIPTION) VALUES
(1, 'Tomato', 'images/ingredients/tomato.webp', 'Red, juicy fruit used as a vegetable.'),
(2, 'Garlic', 'images/ingredients/garlic.avif', 'Pungent bulb used for flavoring.'),
(3, 'Olive Oil', 'images/ingredients/oliveoil.jpg', 'Liquid fat extracted from olives.'),
(4, 'Chicken Breast', 'images/ingredients/chickenbreast.png', 'Lean poultry meat.'),
(5, 'Pasta', 'images/ingredients/pasta.jpg', 'Wheat-based noodles.'),
(6, 'Salt', 'images/ingredients/salt.webp', 'Essential mineral seasoning.'),
(7, 'Black Pepper', 'images/ingredients/blackpepper.jpg', 'Spicy ground peppercorns.'),
(8, 'Rice', 'images/ingredients/rice.webp', 'Starchy grain.'),
(9, 'Onion', 'images/ingredients/onion.jpg', 'Aromatic bulb vegetable.'),
(10, 'Eggs', 'images/ingredients/eggs.webp', 'Poultry eggs, commonly chicken.'),
(11, 'Flour', 'images/ingredients/flour.webp', 'Milled wheat powder.'),
(12, 'Sugar', 'images/ingredients/sugar.jpg', 'Sweet crystalline substance.'),
(13, 'Basil', 'images/ingredients/basil.jpg', 'Green and aromatic herb.'),
(14, 'Rosemary', 'images/ingredients/rosemary.webp', 'Fragrant, evergreen, needle-like leaves'),
(15, 'Parsley', 'images/ingredients/parsley.jpg', 'Mediterranean herb, spice, and vegetable'),
(16, 'Butter', 'images/ingredients/Butter.webp', 'Used as a fat in baking, sauce-making, and pan frying.'),
(17, 'Milk', 'images/ingredients/milk.avif', 'Cow milk.'),
(18, 'Chives', 'images/ingredients/chives.webp', 'Flavoring herb that provides a somewhat mild onion-like flavor.'),
(19, 'Chicken Broth', 'images/ingredients/chickenbroth.jpg', 'Savory, from simmering chicken.'),
(20, 'Bell Pepper', 'images/ingredients/bellpepper.jpg', 'A sweet pepper of many colors.'),
(21, 'Zucchini', 'images/ingredients/zucchini.jpg', 'Best medium to small for texture (accordding to the USDA).'),
(22, 'Green Onion', 'images/ingredients/greenonion.jpg', 'Milder than most onions.'),
(23, 'Mozzarella', 'images/ingredients/mozzarella.jpg', 'Semi-soft non-aged cheese prepared using the pasta filatas method.'),
(24, 'Olives', 'images/ingredients/Olives.webp', 'A staple in Mediterranean diets.'),
(25, 'Pepperoncini', 'images/ingredients/Pepperoncini.jpg', 'Small, delicate peppers usually found in pickled jars.'),
(26, 'Vinaigrette', 'images/ingredients/Vinaigrette.jpg', 'Dressing made from mixing oil with acid.');