-- Entries were AI generated
INSERT INTO INGREDIENTS (INGREDIENT_ID, INGREDIENT_NAME, INGREDIENT_IMAGE_PATH, INGREDIENT_DESCRIPTION, BASE_INGREDIENT_ID) VALUES
(1, 'Tomato', 'images/ingredients/tomato.webp', 'Red, juicy fruit used as a vegetable.', NULL),
(2, 'Garlic', 'images/ingredients/garlic.avif', 'Pungent bulb used for flavoring.', NULL),
(3, 'Olive Oil', 'images/ingredients/oliveoil.jpg', 'Liquid fat extracted from olives.', NULL),
(4, 'Chicken', 'images/ingredients/Chicken.jpg', 'Most common form of poultry.', NULL),
(5, 'Noodle', 'images/ingredients/noodle.avif', 'Long strips of unleavened dough.', NULL),
(6, 'Salt', 'images/ingredients/salt.webp', 'Essential mineral seasoning.', NULL),
(7, 'Black Pepper', 'images/ingredients/blackpepper.jpg', 'Spicy ground peppercorns.', NULL),
(8, 'Rice', 'images/ingredients/rice.webp', 'Starchy grain.', NULL),
(9, 'Onion', 'images/ingredients/onion.jpg', 'Aromatic bulb vegetable.', NULL),
(10, 'Eggs', 'images/ingredients/eggs.webp', 'Poultry eggs, commonly chicken.', NULL),
(11, 'Flour', 'images/ingredients/flour.webp', 'Milled wheat powder.', NULL),
(12, 'Sugar', 'images/ingredients/sugar.jpg', 'Sweet crystalline substance.', NULL),
(13, 'Basil', 'images/ingredients/basil.jpg', 'Green and aromatic herb.', NULL),
(14, 'Rosemary', 'images/ingredients/rosemary.webp', 'Fragrant, evergreen, needle-like leaves', NULL),
(15, 'Parsley', 'images/ingredients/parsley.jpg', 'Mediterranean herb, spice, and vegetable', NULL),
(16, 'Butter', 'images/ingredients/Butter.webp', 'Used as a fat in baking, sauce-making, and pan frying.', NULL),
(17, 'Milk', 'images/ingredients/milk.avif', 'Cow milk.', NULL),
(18, 'Chives', 'images/ingredients/chives.webp', 'Flavoring herb that provides a somewhat mild onion-like flavor.', NULL),
(19, 'Chicken Broth', 'images/ingredients/chickenbroth.jpg', 'Savory, from simmering chicken.', NULL),
(20, 'Bell Pepper', 'images/ingredients/bellpepper.jpg', 'A sweet pepper of many colors.', NULL),
(21, 'Zucchini', 'images/ingredients/zucchini.jpg', 'Best medium to small for texture (accordding to the USDA).', NULL),
(22, 'Green Onion', 'images/ingredients/greenonion.jpg', 'Milder than most onions.', NULL),
(23, 'Cheese', 'images/ingredients/cheese.avif', 'Dairy product from curdling milk.', NULL),
(24, 'Olives', 'images/ingredients/Olives.webp', 'A staple in Mediterranean diets.', NULL),
(25, 'Pepperoncini', 'images/ingredients/Pepperoncini.jpg', 'Small, delicate peppers usually found in pickled jars.', NULL),
(26, 'Vinaigrette', 'images/ingredients/Vinaigrette.jpg', 'Dressing made from mixing oil with acid.', NULL),
(27, 'Canola Oil', 'images/ingredients/canolaoil.jpg', 'Light flavor, high smoke point, and smooth texture.', NULL),
(28, 'Yeast', 'images/ingredients/yeast.jpg', 'Used for fermentation and leavening.', NULL),
(29, 'Thyme', 'images/ingredients/thyme.jpg', 'Aromatic evergreen herb from the mint family.', NULL),
(30, 'Sesame Oil', 'images/ingredients/sesameoil.jpg', 'For stir-frying, marinades, and as a finishing oil to add nutty flavor.', NULL),
(31, 'Pea', 'images/ingredients/pea.webp', 'Hardy cool-season legumes.', NULL),
(32, 'Carrot', 'images/ingredients/carrot.webp', 'Root regetable available in every season.', NULL),
(33, 'Soy Sauce', 'images/ingredients/soysauce.webp', 'Umami and salty.', NULL),
(34, 'Corn', 'images/ingredients/corn.webp', 'Staple crop for many parts of the world.', NULL),
(35, 'Chicken Breast', 'images/ingredients/chickenbreast.png', 'Lean poultry meat.', 4),
(36, 'Cherry Tomato', 'images/ingredients/cherrytomato.jpg', 'Smaller and firmer than normal tomatoes.', 1),
(37, 'Granulated Sugar', 'images/ingredients/granulatedsugar.jpg', 'Granulated sugar is the most commonly used sugar in recipes.', 12),
(38, 'Mozzarella', 'images/ingredients/mozzarella.jpg', 'Semi-soft non-aged cheese prepared using the pasta filatas method.', 23),
(39, 'Pasta', 'images/ingredients/pasta.jpg', 'Wheat-based noodles.', 5),
(40, 'Spaghetti', 'images/ingredients/spaghetti.jpg', 'Long, thin, solid, cylindrical pasta.', 39),
(41, 'Extra Virgin Olive Oil', 'images/ingredients/extravirginoliveoil.jpg', 'Cold-pressed and strictly-scrutinized.', 3),
(42, 'Unsalted Butter', 'images/ingredients/unsaltedbutter.jpg', 'Butter but unsaltted.', 16),
(43, 'Salted Butter', 'images/ingredients/saltedbutter.webp', 'Butter but saltted.', 16),
(44, 'Fusilli', 'images/ingredients/fusilli.jpg', '"Little spindles", twisty pasta.', 39),
(45, 'All-Purpose Flour', 'images/ingredients/allpurposeflour.jpg', 'Mid-strength, medium-gluten flour.', 11),
(46, 'Baking Soda', 'images/ingredients/bakingsoda.avif', 'Primarily used in baking as a leavening agent.', NULL),
(47, 'Baking Powder', 'images/ingredients/bakingpowder.avif', 'Dry chemical leavening agent, containing the acid needed for baking soda.', NULL),
(48, 'Vanilla Extract', 'images/ingredients/vanillaextract.png', 'Primary vanilla, but charactistically deep and complex.', NULL),
(49, 'Bacon', 'images/ingredients/bacon.webp', 'Salt-cured pork, highly fatty.', NULL),
(50, 'Lettuce', 'images/ingredients/lettuce.webp', 'Cool-weather leafy green.', NULL),
(51, 'Bread', 'images/ingredients/bread.jpg', 'Staple food product.', NULL),
(52, 'Mayonnaise', 'images/ingredients/mayonnaise.jpg', 'Emulsion of oil, egg yolk, and an acid.', NULL);
