-- Generated by AI
INSERT INTO RECIPES_FEATURE_CUISINES (RECIPE_ID, CUISINE_ID) VALUES
(1, 1), -- Pomodoro: Italian
(2, 6), -- Garlic Chicken: American
(3, 4), -- Rice: Chinese
(3, 5), -- Rice: Japanese
(4, 6), -- Scrambled Eggs: American
(5, 6), -- Tomato Soup: American
(6, 1), -- Pasta Salad: Italian
(7, 7), -- Bread: French
(8, 7), -- Onions: French
(9, 4), -- Fried Rice: Chinese
(10, 6); -- Cookies: American