-- Recipes are AI generated. Try at your own risk.
INSERT INTO RECIPES (RECIPE_ID, RECIPE_NAME, RECIPE_IMAGE_PATH, RECIPE_DESCRIPTION, INSTRUCTIONS, TOTAL_MINUTES, COURSE, AI_GEN_DESCRIPTION, AI_GEN_APPLIANCES, AI_GEN_CUISINES, AI_GEN_DISH_TYPES, AI_GEN_TOTAL_MINUTES, AI_GEN_COURSE, AUTHOR_ID, RECIPE_STATUS) VALUES
(1, 'Spaghetti Pomodoro', 'images/recipes/pomodoro.webp', 'A simple classic Italian pasta dish.', '1. Boil pasta. 2. Sauté garlic in olive oil. 3. Add tomatoes. 4. Mix with pasta.', 30, 'Entrée', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1, 'Active'),
(2, 'Garlic Chicken', 'images/recipes/garlic_chicken.jpg', 'Juicy pan-seared chicken with garlic.', '1. Season chicken. 2. Heat oil in pan. 3. Cook chicken for 4-5 minutes. 4. Flip and cook for 3-4 more minutes 5. Add garlic until fragrant. 6. Add rice.', 25, 'Entrée', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, 3, 'Active'),
(3, 'Basic White Rice', 'images/recipes/rice.webp', 'Fluffy steamed white rice.', '1. Rinse rice. 2. Add water. 3. Cook in rice cooker until done.', 20, 'Appetizer / Side', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 4, 'Active'),
(4, 'Scrambled Eggs', 'images/recipes/scrambledeggs.jpg', 'Quick and easy breakfast eggs.', '1. Whisk eggs. 2. Add milk and whsik again. 3. Heat pan with oil or butter. 4. Cook eggs gently while stirring. 5. Season and garnish', 10, 'Entrée', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 5, 'Active'),
(5, 'Tomato Soup', 'images/recipes/tomatosoup.jpg', 'Warm and comforting tomato soup.', '1. Roast cut tomato 2. Lightly mix cut tomatoes, diced onion, chopped garlic, salt, pepper, and olive oil. 3. Roast again, for 15 minutes. 4. Stir. 5. Bake for 15 minutes (again).  6. Blend on high speed until smooth. 7. Melt butter over medium-high heat. 8. Add flour to melted butter and mix. 9. Cook until mixture is bubbly and slightly thickened. 10. Add broth and sugar and mix. 11. Add blended mixure from earlier. 12. Add milk. 13. Cook on medium-low for 15 minutes, adding salt and pepper as needed. 14. Serve.', 120, 'Appetizer / Side', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 2, 'Active'),
(6, 'Pasta Salad', 'images/recipes/pastasalad.jpg', 'Cold pasta mixed with vegetables.', '1. Boil and cool pasta. 2. Chop vegetables and mozzarella. 3. Mix all ingredients. 4. Let set for 30 minutes so flavors can meld.', 60, 'Appetizer / Side', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1, 'Active'),
(7, 'Homemade Bread', 'images/recipes/bread.jpg', 'Simple baked artisan loaf.', '1. Proof yeast by adding water and pinch of sugar and sitting for 5-10 minutes. If yeast does not foam, then start over with fresh yeast. 2. Add sugar, salt, oil, and 3 cups of flour and mix. 3. Add another cup of flour and mix. 4. While the mixer is running, add half cups of flour until the dough begins to pull away from the side. 4. Mix on medium/knead by hand for five minutes. 5. Grease a bowl with oil and place the dough inside, covering the bowl with food wrap. 6. Sit in a warm place and let rise for 1.5 hours. 7. Punch dough to remove air bubbles. 8. Divide into equal portions, shape each into long logs, and place into loaf pans. 9. Spray plasgtic wrap with cooking spray and cover for 45-60 minutes, or until the dough has risen an inch above the loaf pans. 10. Preheat oven to 350 degrees Fahrenheit. 11. Place bread on lower or middle rack and bake for 30-33 minutes, or when top is golden brown. 12. Let sit for 15 minutes', 240, 'Appetizer / Side', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 9, 'Active'),
(8, 'Caramelized Onions', 'images/recipes/caramelizedonions.jpg', 'Sweet and savory slow-cooked onions.', '1. Slice onions and thyme. 2. Heat oil on skillet over medium heat. 3. Add onions and cook, tossing and stir occasionally for 15-20 minutes, or until softened. 4. Reduce heat to low and toss/stir occasionally for 50-60 minutes, or until onions are completely soft and caramelized. 5. Remove onions from skillet and add salt, pepper, and thyme.', 90, 'Appetizer / Side', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 1, 'Active'),
(9, 'Chicken Fried Rice', 'images/recipes/chickenfriedrice.jpg', 'Leftover rice stir-fried with chicken.', '1. Cook chicken. 2. Add day-old rice and egg. 3. Stir fry together.', 15, 'Entrée', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 4, 'Active'),
(10, 'Simple Sugar Cookies', 'images/recipes/cookies.jpg', 'Classic sweet baked treats.', '1. Proof yeast by adding water and honey and sitting for 5-10 minutes. 2. Form cookies. 3. Bake.', 60, 'Dessert', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 2, 'Active'),
(11, 'FREE IPHONE RECIPE', NULL, 'Click here for a free phone www.scam.com', '1. Go to link. 2. Give SSN.', 5, 'Entrée', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 12, 'Banned'),
(12, 'Bleach Cleanse Smoothie', NULL, 'Cure everything with this smoothie.', '1. Mix bleach and ammonia. 2. Drink.', 10, 'Appetizer / Side', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 11, 'Banned'),
(13, 'KFC 11 Herbs Secret', NULL, 'This is the exact stolen proprietary recipe.', '1. Fry chicken. 2. Use secret stolen blend.', 60, 'Entrée', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 13, 'Banned');